# Generated by Django 5.1 on 2024-08-29 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_remove_question_user_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='context',
            new_name='matchText',
        ),
    ]
