# Generated by Django 5.1 on 2024-08-29 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_alter_question_matchtext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='matchText',
            field=models.TextField(blank=True, null=True),
        ),
    ]
