# Generated by Django 5.1 on 2024-09-01 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_alter_question_matchtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
